### ISSUE TITLE
Dialog Box does not possition itself beside point

### ISSUE THREAD

**Issue by mofman** [waynegm/imgNotes#11]
Using latest build dialog box is always at bottom left hand side of image container

**Comment by waynegm** [comment]
I'm not seeing this issue either in my local build or the [demo site](http://waynegm.github.io/imgNotes/). What versions of jQuery and jQueryUI are you using?

**Comment by mofman** [comment]
It does actually appear to be happening on your demo site (
http://waynegm.github.io/imgNotes/examples/basic_interactive.html ), when
you drop a pin the dialog doesn't appear beside the pin, always to the far
left. Using your build from 12 Sep 2014 it works fine.
https://github.com/waynegm/imgNotes/releases

**Comment by waynegm** [comment]
Your right, just had to make my browser window bigger to emphasise the problem. I've just pushed a change to Master that appears to fix this and updated the demos accordingly. Let me know if it now works for you and I'll tag a new release.

**Comment by mofman** [comment]
Looks good now wayne if you want to do a new build.

Thanks

**Comment by waynegm** [comment]
Tagged it as 0.7.5 - cheers
