### ISSUE TITLE
not working on dynamically loaded image

### ISSUE THREAD

**Issue by wktest99** [waynegm/imgNotes#12]
not working on dynamically loaded image. how to solve now?

**Comment by waynegm** [comment]
Can you give me a link to a page showing the problem?

**Comment by wktest99** [comment]
solved it by adding dom elements. but now i have another problem when i removing the element already applied the imagenote it hangs for some time. i am removing the element using .html()

so is there any way I can destroy all imagenote object related things and can recreate it for another dynamically loaded image. please help

**Comment by waynegm** [comment]
Using $("#image").imageNotes("destroy") should clean everythng up.

**Comment by waynegm** [comment]
Presuming this has been resolved - if not please reopen.

**Comment by griffero** [comment]
I'am having the same issue here. I'am developing a web2py application and using imgNotes over certain view. The error that I get is:

> $("#exercise-image").imgNotes is not a function. (In '$("#exercise-image").imgNotes()', '$("#exercise-image").imgNotes' is undefined)

where excercise-image is de ID of the image that is being used.

The JS is the following:

`//
    
    $(document).ready(function(){

        function activateViewManager(){
            var $img = $("#exercise-image").imgNotes();
        }

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#exercise-image').attr('src', e.target.result);
                    $("#first-part-form").hide();
                    $("#second-part-form").show();
                    activateViewManager();
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#question-image-upload-btn').change(function () { 
            if(isValidInput() == true){ 
                readURL(this);
                changeQuestionElements();
            } 
        });

    // Other code over here..
    });
`

**Comment by griffero** [comment]
I'am having the same issue here. I'am developing a web2py application and using imgNotes over certain view. The error that I get is:

> $("#exercise-image").imgNotes is not a function. (In '$("#exercise-image").imgNotes()', '$("#exercise-image").imgNotes' is undefined)

where excercise-image is de ID of the image that is being used.

The JS is the following:


    
    $(document).ready(function(){

        function activateViewManager(){
            var $img = $("#exercise-image").imgNotes();
        }

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#exercise-image').attr('src', e.target.result);
                    $("#first-part-form").hide();
                    $("#second-part-form").show();
                    activateViewManager();
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#question-image-upload-btn').change(function () { 
            if(isValidInput() == true){ 
                readURL(this);
                changeQuestionElements();
            } 
        });

    // Other code over here..
    });

**Comment by waynegm** [comment]
Is it possible that there is no image associated with #exercise-image when
the imgNotes plugin is attached to the selector?

Also n reader.onload you should destroy the attached imgNote before
changing the image source ie

reader.onload(e) {
   $('#exercise-image').imgNotes(destroy);
   $('#exercise-image').attr('src',e.target.result);
   ...

**Comment by griffero** [comment]
Thanks you for your time and the fast response. It was a problem with web2py not related with the plugin, so I deleted the question. The problem was fixed and ImgNotes is working well now.
