### ISSUE TITLE
Zoom doesn't seem to work properly on touch devices

### ISSUE THREAD

**Issue by pwcueblocks** [waynegm/imgNotes#17]
When zooming in touch devices, the image weirdly jumps, flickers and when finished zooming the image jumps somewhere else and the same issue persists with demo version also.

**Comment by waynegm** [comment]
Apologies I haven't found a satisfactory solution for handling touch gestures and mouse together. However, I've updated the Master and demo pages with a more recent version of the underlying imgViewer plugin where I've been trying to improve the touch experience. This should give better response to pinch gestures but is still a bit awkward for dragging.

**Comment by pwcueblocks** [comment]
Thanks, Wayne for help.
I have checked and its seems working better now.

**Comment by xjirman** [comment]
hi Wayne! First of all thank you for the plugin, it's exactly what I was looking for! The pinch zoom works great now.

I was wondering if you have an ETA in your mind for nailing the drag gestures on mobile devices?

**Comment by waynegm** [comment]
Hey I've replaced the code for handling touch gestures in the imgViewer widget with [jquery.event.ue.js](https://github.com/mmikowski/jquery.event.ue). This seems to work much better. There  are no changes to the external interface for either the imgViewer or imgNotes widget. GitHub master for each widget and the respective demo sites contain the update. If you get a chance give it a try and let me know if its working better for you as well.

**Comment by xjirman** [comment]
Hi Wayne,

I've updated the libraries to the latest version and it seems to be working well (tested on iPhone6). I'll let you know if something crops up. 

Thank you so much for fixing it in such short time! Do you have any "buy me a coffee" button anywhere :)?

Cheers!
David

**Comment by waynegm** [comment]
David,
Thanks are enough. I put my code out there for others to use to give back to the community that gave me the Linux OS and other open source software that I run on my main pc.

Wayne
