### ISSUE TITLE
Scrolling page on mobile

### ISSUE THREAD

**Issue by GoncaloJoaoCorreia** [waynegm/imgNotes#18]
Even with the `zoomable` flag set to false, when trying to scroll a page with an image with notes the page can only be scrolled when touching outside the image. Is there a way to make the page scrolling/zoom work normally on touch devices?

**Comment by waynegm** [comment]
I've been trying out different libraries to improve the touch support so apologies if things have changed. I've just pushed to master (what will be 0.9.0) an implementation using [hammer.js](http://hammerjs.github.io/) for touch support. This offers more flexibility than the library I tried in 0.8.0. Have a look at the current demos and you will see I've added one where you can turn off zoom and drag separately. My testing of this hasn't revealed any issues but am interested in hearing if it works for you.

**Comment by GoncaloJoaoCorreia** [comment]
I've switched to the new version of the code and it appears to be working well with the new draggable flag, at least on the devices I use to test. I had been using a workaround with disabled panning of the image, but this is much better. Thanks!
