### ISSUE TITLE
Help needed,issue plotting markers

### ISSUE THREAD

**Issue by vhenriques** [waynegm/imgNotes#19]
I have a layout of a building on which i need to place markers and provide zoom functionality,
i have a rest service which returns the following values and the formula used on these values is as follows

```
var pixelsPerUnit = imageHeightinPX  /  siteHeightInFeet;
var xPos = xPos * pixelsPerUnit; //where xPos is pos of item in building
var yPos = yPos * pixelsPerUnit; //where yPos is pos of item in building
```

i then save this data in an array
and give it to imgNotes

` $img.imgNotes("import", JSON.parse(JSON.stringify(coordPos)) );`
where coordPos data is as follows

```
JSON.stringify(coordPos)
'[{"x":"1062.9795263337062","y":"608.1403686232554","note":"test01532a005"},{"x":"1065.3661041676799","y":"1076.7723775713662","note":"test01532a004"},{"x":"1455.4987501823664","y":"1364.618314448281","note":"test01532a008"},{"x":"847.9298156883724","y":"1670.2123231046055","note":"test01532a003"},{"x":"2040.6921169090115","y":"843.6384574235277","note":"test01532a051"},{"x":"2035.9413704226038","y":"455.89238924281483","note":"test01532a050"},{"x":"1719.5461362641638","y":"608.1403686232554","note":"test01532a007"},{"x":"2035.9413704226038","y":"1507.3423916743666","note":"test01532a002"},{"x":"1396.0247823761124","y":"612.891115109663","note":"test01532a006"}]';
```

My image dimens are 3456*2304

***To test the issue i took my image and stubbed the json values i get and inserted it into the provided basic_interactive.html example.
In the example
default plotting values i changed as follows***

```
$img.imgNotes("import", [	{x: "1062.9795263337062", y:"608.1403686232554", note:"test"}, //custom data
									{x: "0.322", y:"0.269", note: "Brisbane Lions Flag"}, //default
									{x: "0.824", y: "0.593", note: "Fluffy microphone"}]); //default
```

***I kept first x,y value from my stubbed data and the rest two the default values as given in the example,
as a result my stubbed value was not plotted but default values 2,3rd values were plotted.***

![capture](https://cloud.githubusercontent.com/assets/3635834/17930422/bf56eb1a-6a23-11e6-98c0-4944a52753d3.PNG)

***ive attached sample html in example folder of the zip for sampling my issue***
[imgNotes-master.zip](https://github.com/waynegm/imgNotes/files/434643/imgNotes-master.zip)

Any pointers to what im doing wrong will be greatly appreciated,
thanks for this great library.

**Comment by waynegm** [comment]
The note locations in the json feed have to be given in relative image coordinates not pixels. Relative image coordinates range between 0 and 1. (0,0) is the top left corner of the image and (1,1) the bottom right corner. You convert a pixel location to relative coordinates by dividing the x pixel location by the image width and the y pixel coordinate by the image height. So for your original 3456 x 2304 (presumably width x height) image the x should be 1063/3456 (ie  0.307581) and the y should be 608/2304 (ie 0.263889).
Cheers,
Wayne

**Comment by vhenriques** [comment]
oh thanks a ton,
A few more doubts
1.is there a way to call the zoom using a method so that i can do it on button clicks too?
2.is there a call back that returns the current zoom level or step 

basically i have a scenario where markers overlap each other,so il have to plot cluster markers and the overlapping markers
so when user is completely zoomed out he sees cluster marker
when he zooms in he sees the markers as il make the cluster marker hidden

but for this is there a way to assign id or class to the markers being drawn so that i can hide unhide them using js/jQ later?
Thanks

**Comment by waynegm** [comment]
You can get/set the zoom using the zoom option:
## zoom
  * Get/Set the current zoom level of the image - must be >= 1
  * Default: 1 (ie the entire image is visible)
  * Example - to display the image magnified 3x:
```javascript
$("#image1").imgNotes("option", "zoom", 3);
```
To customise the markers define your own onAdd callback
## onAdd
  * Callback triggered when a marker/note is added to the widget to allow developers to define their own markers. This will happen when notes are imported using the "import" method and when the user clicks on the widget in edit mode. Within the callback "this" refers to the imgNotes widget.
  * Default: Inserts a numbered inverted black teardrop image aligned to point at the insertion point
  * Callback Arguments: none
  * Callback Returns: the new marker element
  * Example:
```javascript
$("#image1").imgNotes("option", "onAdd", function() {
	this.options.vAll = "bottom";
	this.options.hAll = "middle";
	return  $(document.createElement('span')).addClass("marker black").html(this.noteCount);
});
```
The examples folder contains some other examples of custom onAdd callbacks.

Wayne

**Comment by vhenriques** [comment]
Thanks for all the help !
