### ISSUE TITLE
Can we add more connection line between markers?

### ISSUE THREAD

**Issue by ollakalla** [waynegm/imgNotes#26]
What i'm trying to do is making 2 connection or more with different colors between markers
I have read[ issue number 10](https://github.com/waynegm/imgNotes/issues/10) ,but it only make one connection between all markers,
so let's say :
i have 5 markers(associated) i want to make connection between them with color Blue 
and 9 markers(unassociated) i want to make connection between them with color Red

when i try the code below it makes connection between all markers with Red color
and the number inside the markers has assigned to all markers so it become 1 to 14
and what it suppose to do is 
make connection between associated markers with Blue
and make connection between unassociated markers with Red
and the number inside marker will be 1 to 5 for associated markers and 1 to 9 for unassociated markers

      function createLine(x1, y1, x2, y2, options)
      {
      defaults = {
        zindex : 10000,
        color : 'blue',
        stroke: "3",
        style: "solid",
      };
      options = $.extend({}, defaults, options);

      if (x2 < x1)
      {
        var temp = x1;
        x1 = x2;
        x2 = temp;
        temp = y1;
        y1 = y2;
        y2 = temp;
      }
      var length = Math.sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2));
          var angle = Math.atan((y2-y1)/(x2-x1));
      var line = $(document.createElement('div')).css({
        left: (x1 - 0.5*length*(1 - Math.cos(angle))) + "px",
        top: (y1 + 0.5*length*Math.sin(angle)) + "px",
        width: length,
        borderBottom: options.stroke + "px " + options.style,
        borderColor: options.color,
        position: "absolute",
        transform: "rotate(" + angle + "rad)"
      });
      return line;
    }

    var $associated = $(".track_map").imgNotes({
      onUpdate: function() {
        var self = this;
      // Delete the lines
        $('.mkr_line').remove();
      // Draw the lines
        var isFirst = true;
        var lastPos;
        $.each(this.notes, function() {
          var $mkr = $(this);
          var pos = $associated.imgViewer("imgToView", $mkr.data("relx"), $mkr.data("rely"));
          if (isFirst === false) {
            var elem = createLine(lastPos.x, lastPos.y, pos.x, pos.y,{color:"blue"});
            elem.addClass('mkr_line');
            $(self.img).imgViewer("addElem",elem);
          }
          lastPos = pos;
          isFirst = false;
        });
      // Show the markers 
        $.each(this.notes, function() {
          self.options.onUpdateMarker.call(self, this);
        });
      }
    });

    var $unassociated = $(".track_map").imgNotes({
      onUpdate: function() {
        var self = this;
      // Delete the lines
        $('.mkr_line').remove();
      // Draw the lines
        var isFirst = true;
        var lastPos;
        $.each(this.notes, function() {
          var $mkr = $(this);
          var pos = $unassociated.imgViewer("imgToView", $mkr.data("relx"), $mkr.data("rely"));
          if (isFirst === false) {
            var elem = createLine(lastPos.x, lastPos.y, pos.x, pos.y,{color:"red"});
            elem.addClass('mkr_line');
            $(self.img).imgViewer("addElem",elem);
          }
          lastPos = pos;
          isFirst = false;
        });
      // Show the markers 
        $.each(this.notes, function() {
          self.options.onUpdateMarker.call(self, this);
        });
      }
    });

    $associated.imgNotes("import", associated_station);
    $unassociated.imgNotes("import", unassociated_station);

**Comment by waynegm** [comment]
By declaring the second "red" "onUpdate" function  you just overwrite the original "blue" one because you are attached to the same image. Likewise calling the import twice for the same image just appends the red notes to the previously imported blue notes. So all the notes (associated and unassociated) are then displayed by the "red" "onUpdate" function as you are seeing.

So you need to do all the display from a single "onUpdate" function and find a way to keep track of which notes are blue and red. If users can't add or delete notes then you could just always load the blue notes first and store how many in a variable (say num_blue). Then in the $.each plotting loop do the blue line for first "num_blue" notes and red line for the rest.

Wayne

**Comment by ollakalla** [comment]
No user can't add or delete notes. he just view markers on map

**Comment by waynegm** [comment]
Something like this may work:
```
var numass;
var $associated = $(".track_map").imgNotes({
  onUpdate: function() {
    var self = this;
  // Delete the lines
    $('.mkr_line').remove();
  // Draw the lines
    var isFirst = true;
    var lastPos;
    var count = 0;
    $.each(this.notes, function() {
      count += 1;
      var $mkr = $(this);
      var pos = $associated.imgViewer("imgToView", $mkr.data("relx"), $mkr.data("rely"));
      if (isFirst === false && count != numass) {
        if (count <= numass) { 
           var elem = createLine(lastPos.x, lastPos.y, pos.x, pos.y,{color:"blue"});
        } else {
           var elem = createLine(lastPos.x, lastPos.y, pos.x, pos.y,{color:"red"});
        }
        elem.addClass('mkr_line');
        $(self.img).imgViewer("addElem",elem);
      }
      lastPos = pos;
      isFirst = false;
    });
  // Show the markers 
    $.each(this.notes, function() {
      self.options.onUpdateMarker.call(self, this);
    });
  }
});

$associated.imgNotes("import", associated_station);
numass = $associated.imgNotes("count");
$associated.imgNotes("import", unassociated_station);
```

**Comment by ollakalla** [comment]
It works fine, but i have another thing.
now i want check by value (type == 1) instead of (count <= numass)
and type is value send in array associated_station
so the associated_station will be like this {x: "0.5", y:"0.5", note:"AFL Grand Final Trophy",type:1}
how can i make it

**Comment by waynegm** [comment]
So is there just 2 types of station? 
Can we assume the stations will be grouped by the "type" parameter?

If the answers are Yes and Yes, I'd probably do this by copying the station type into a global variable:
```
stationType = associated_station.map(function(item) {
     return item.type;
});
```
before doing the import. Then in the onUpdate function step through the stationType array at the same time:
```
var lastType;
$.each(this.notes, function(index,value) {
      var $mkr = $(value);
      var type = stationType[index];
      var pos = $associated.imgViewer("imgToView", $mkr.data("relx"), $mkr.data("rely"));
      if (isFirst === false && type ===lastType) {
        if (type === 1) { 
           var elem = createLine(lastPos.x, lastPos.y, pos.x, pos.y,{color:"blue"});
        } else {
           var elem = createLine(lastPos.x, lastPos.y, pos.x, pos.y,{color:"red"});
        }
        elem.addClass('mkr_line');
        $(self.img).imgViewer("addElem",elem);
      }
      lastPos = pos;
      lastType = type;
      isFirst = false;
    });
```

**Comment by ollakalla** [comment]
Perfect this is exactly what i want,
Thanks so much Wayne :)
