### ISSUE TITLE
imgNotes importajax

### ISSUE THREAD

**Issue by skainz1944** [waynegm/imgNotes#29]
Hello, 
first of all, thank you for putting in so much effort for this excellent plugin. 
Second, im using it for a project of mine, and have extended it by an importajax function, which extends the import function by doing an ajax request before it adds the markers. 
I think i will do some more improvements or add functionality along my project.
Interessted in some help/contributions?

regards,

**Comment by waynegm** [comment]
Any contribution that enhances the core functionality would be welcome.
