### ISSUE TITLE
Use with Vue

### ISSUE THREAD

**Issue by lynn2017** [waynegm/imgNotes#34]
Could this plugin be used with Vue.js?

**Comment by waynegm** [comment]
I don't know anything about Vuejs but Googling "jquery plugin vuejs" turned up lots of hits. There seem to be issues with including jquery plugins like imgNotes that require the DOM to be ready in Vuejs.  However,  these appear be resolved by instantiating the plugins in the right place (inside the Vue ready or mounted function) though sometimes a timer is needed. Only way to know is to give it a try.

**Comment by lynn2017** [comment]
Thanks!
