### ISSUE TITLE
conflict 

### ISSUE THREAD

**Issue by smed2717** [waynegm/imgNotes#35]
There is a problem when I try to change the <img> ($ ('# image') tag attr ('src', 'image / test_new_image.jpg');
) By applying the plugin imgNote

Thank you for your colloboration

**Comment by waynegm** [comment]
As it is you can't change the image after the imgNote is created. Instead you have to destroy the imgNote using ```imgNotes("destroy")``` update the image tag src and then reattach the imgNotes plugin.

**Comment by smed2717** [comment]
Hi,

thanks for your help
