### ISSUE TITLE
zoom issue 

### ISSUE THREAD

**Issue by lynn2017** [waynegm/imgNotes#36]
Hi,

When I disabled the image zoomable setting and zoomed in the whole page, then click the image to add notes, the image position is wield. 

It looked like below. 

Do you have any ideas to fix it? 

![image](https://cloud.githubusercontent.com/assets/17437817/23840111/70084672-0770-11e7-9e1f-14e8efa13c90.png)

**Comment by waynegm** [comment]
I'm preparing a new release and I think this is now fixed. Have a look at this [example](http://waynegm.github.io/imgNotes/basic_editor.html) in the new master branch which will become the 1.0.0 release once I tidy up the docs.
