### ISSUE TITLE
Ie 11 browser isssue

### ISSUE THREAD

**Issue by yashascelstream** [waynegm/imgNotes#37]
On edit add marker doesnt show up in ie 11

**Comment by waynegm** [comment]
I've been making a few changes in preparation for a 1.0.0 release and I think this is now fixed. Have a look at the [example ](http://waynegm.github.io/imgNotes/basic_editor.html) that uses the updates in the master branch and see if that works for you.

**Comment by yashascelstream** [comment]
What are the changes have you made.if I include js files are they enough.

**Comment by yashascelstream** [comment]
It's not working for me.

**Comment by waynegm** [comment]
What isn't working - the example or using the plugin in your own code? The example on Github works for me in IE11 in a Windows 7 virtual machine.

**Comment by yashascelstream** [comment]
Using plugin in my code.cursorToimg here it stucks.n doesn't return anything.no error too.

**Comment by waynegm** [comment]
Please check you are using  the 1.0.0 (latest) version of my imgViewer plugin and not an old version.

**Comment by yashascelstream** [comment]
Thanks.its working for me.
