### ISSUE TITLE
Add marker via right click

### ISSUE THREAD

**Issue by yashascelstream** [waynegm/imgNotes#38]
Can we initiate via right click

**Comment by waynegm** [comment]
If you want to do that suggest you extend the plugin, see [Extending Widgets with the Widget Factory](https://learn.jquery.com/jquery-ui/widget-factory/extending-widgets/), and redefine the addNote method just changing $elem.click to $elem.contextmenu.

**Comment by waynegm** [comment]
Actually what I just messaged is incorrect there is no easy way to bind to right mouse clicks - sorry.

**Comment by yashascelstream** [comment]
Any work around.i see that your using tap event  of hammer js.it is not allowing right click.

**Comment by waynegm** [comment]
I dont' think it's available in hammerJS. Could bind directly to the jquery mouse event - I'm just not sure whether you could do it without changing the plugin source. I'll have a look.

**Comment by waynegm** [comment]
It's a bit of a hack but have a look at lines 96-101 of the attached which inserts markers on right click. Obviously someone on a touch device will have no way of adding markers with this active.
[test.zip](https://github.com/waynegm/imgNotes/files/847607/test.zip)

**Comment by yashascelstream** [comment]
Thanks..It's working fine
