### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by smed2717** [waynegm/imgNotes#39]
Is it possible to note a pdf document?

**Comment by waynegm** [comment]
Not directly. You could use pdf.js to convert the pdf to an image and then add notes on the image. See http://usefulangle.com/post/24/pdf-to-jpeg-png-with-pdfjs for an example.

**Comment by smed2717** [comment]
Thanks for your help

2017-04-04 10:51 GMT+01:00 Wayne Mogg <notifications@github.com>:
