### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by romileon** [waynegm/imgNotes#4]
hi! really great jquery! im trying to use it and i keep getting this error on imgNotes.js: $img.imgViewer is not a function...

**Comment by KaushalNaresh9** [comment]
Hi I am getting this weird error $bigImg.imgNotes is not a function. Please help me out.

**Comment by waynegm** [comment]
Can you provide the code/page where this occurs otherwise I'd just be guessing in the dark as to the cause.

**Comment by KaushalNaresh9** [comment]
Actually prev error is resolved but now there is another error where imgNotes is not able to call onEdit option.
[displayEvidencesWithInteractivePointers.jsp.zip](https://github.com/waynegm/imgNotes/files/7256905/displayEvidencesWithInteractivePointers.jsp.zip)

**Comment by KaushalNaresh9** [comment]
I have included these files also

<link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" media="screen">

<link rel="stylesheet" src="/js/imgNotes-master/src/imgNotes.css">

<script type="text/javascript" src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="/js/hammer.min.js"></script>
<script src="/js/jquery.hammer.js-master/jquery.hammer.js"></script>
<script src="/js/jquery-mousewheel-main/jquery.mousewheel.min.js"></script>
<script src="/js/imgViewer-master/docs/lib/imgViewer.js"></script>
<script src="/js/imgNotes-master/src/imgNotes.js"></script>

**Comment by waynegm** [comment]
Try changing:
$img1 = $bigImg.imgNotes({ onEdit: cust_onEdit });
to
$img1 = $bigImg.imgNotes("option", "onEdit", cust_onEdit);

**Comment by KaushalNaresh9** [comment]
Hi,

How can we use imgViewer options in imgNotes?? 

I want to use onReady function apart from other imgNotes options.

$img.imgNotes({ 
                    onEdit: function( ev, elem) {
                        
                    }, onUpdateMarker: function(elem) {
                        
                        }
                    },
                    onReady: function() {
        		alert("hello");
    	            }
                });
                
if I use onReady function like this then it is not working. Please help me out.

**Comment by waynegm** [comment]
You have got too many "}" in the definition of onUpdateMarker. Replace:
```
onUpdateMarker: function(elem) {
                         
                         }
                     },

with :
```
onUpdateMarker: function(elem) {
                         
                     },

**Comment by KaushalNaresh9** [comment]
That was added by mistake here, but in my original code there is no such bracket error. But still it is not working. Actually I want to trigger a click event on image manually using jquery so that when I open image then pointer automatically gets attached to that specific place. Is this possible to do here??

**Comment by waynegm** [comment]
After I removed the excess brace the alert shows for me. If it isn't working for you then there must be a problem elsewhere on your page. 

Have a look at this [example](http://waynegm.github.io/imgNotes/basic_viewer.html) from Github that attaches markers to locations on an image from javascript.
