### ISSUE TITLE
 Support Angular 1.x

### ISSUE THREAD

**Issue by iiitmahesh** [waynegm/imgNotes#40]
**(How to use ImgNotes in angular )**
I want to use this imageNotes in my angualr project. I have included this and tried different ways, but getting lots of error messages....... FInally after putting lot of time and effrot, I came to know that, I need to initiate a angular diretive fot this, but I am new angular. Can any one provide some suggestions or guidelines to convert this into angular directive.

**Comment by waynegm** [comment]
Likewise I have no experience with Angular so I can't be of any help. You may be better seeking help on an Angular specific forum.
