### ISSUE TITLE
Placing duplicate pins.

### ISSUE THREAD

**Issue by Amirsohal** [waynegm/imgNotes#42]
imgNotes is placing duplicate pins on image. I am storing pin's co-ordinates in database in percentage. When its drawing the pins on the image, its showing the proper pin on img tag created by imgNotes (means its properly calculating the pixel value for the co-ordinates) and also placing the duplicate pin on the original img tag which is written in html. Its taking the co-ordinate percent value as a pixel value for original img tag. So its showing duplicate pin on original img tag on extreme top left corner.
For example :- If pin is placed in exact center point I am storing x any y co-ordinates in percentage i.e. x=0.5 and y=0.5. While fetching the pin from database its showing one pin properly at center on image created by imgNotes. And duplicate pin is placed with original img tag with style property left = 05px and top = 0.5px. 

Could you please help me to sort it out.

**Comment by waynegm** [comment]
Is this happening when you use the addNote or import methods? Can you share the code around where you are adding the notes to the plugin?

**Comment by Amirsohal** [comment]
This is happening when I am using import method. I am just passing my co-ordinates and other data to import method. In my scenario I dont want to use note on pin. I am just want add pin on image.

**Comment by waynegm** [comment]
Do you get the same issue if you display the examples from the Github project page eg at this  [link](http://waynegm.github.io/imgNotes/basic_viewer.html). If not then it eliminates browser compatibility issues and I'd be thinking it's an issue with your code. It's really hard to try and solve the problem without seeing some code that produces the problem.

**Comment by Amirsohal** [comment]
No, I am not getting any issue from demo link. Its issue with my code. I have corrected it and its working fine. @waynegm  Thanks for your quick and valuable response :)
