### ISSUE TITLE
additional properties for a marker

### ISSUE THREAD

**Issue by raku** [waynegm/imgNotes#45]
Hello,

Can I add additional properties for a marker diffent from note?

Thanks.

**Comment by waynegm** [comment]
It should be possible. You will probably need to use imgNotes as a guide and create your own extension to the imgViewer plugin which supports the additional properties you need. If that seems too difficult you could also consider an extension to my [imgViwer2](https://github.com/waynegm/imgViewer2) plugin. The imgViewer2 examples show how to create a simple imgNote equivalent with a lot less code.

**Comment by raku** [comment]
:) If I'm right you are using leaflet in version 2, this is what I'have used for getting what I need, I'm setting in Layer Feature properties that I need to store, something like this:


```
feature = layer.feature = layer.feature \|\| {}; // Intialize `layer.feature`
feature.type = feature.type \|\| "Feature"; // Intialize feature.type
var props = feature.properties = feature.properties \|\| {}; // Intialize feature.properties
var curPos = layer.getLatLng();
props.name = 'Name ' + curPos.lat + '-' + curPos.lng; // just an example
props.code = 'Code ' + curPos.lat + '-' + curPos.lng; // just an example

```
