### ISSUE TITLE
Blur Image plotted, a height and width related issue.

### ISSUE THREAD

**Issue by Prashanth-Thomas** [waynegm/imgNotes#47]
I have a massive image to plot, i need the map to take fixed height, so i give height=300 and the width=500
I have provided this height and width on the image Tag

I assumed that giant image wouldn't resize to the size mentioned in the img tag. 

**The result:** 
A blur and crushed version of the image gets loaded initially, following which the plot points show up on the blur crushed image.

**Expected working:**
It should form a window using which i can move and zoom the uncrushed, clear, original version of the image.

How would i go about achieving the 'Expected working'?

**Comment by waynegm** [comment]
The default behaviour should be for the server to send the full image so I wouldn't expect the image to be physically resized unless the server is set to automatically resize images to optimize page load times. How are you testing this? Do you get the same behaviour loading the image and html page from your local disk?
